# Generated by Django 4.1.5 on 2024-03-30 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_rename_venta_saledetail_sale_and_more"),
        ("products", "0004_alter_category_options_alter_product_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Hotel",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="Room",
        ),
    ]
